### ISSUE TITLE
Create wiki

### ISSUE THREAD

**Issue by JnRouvignac** [tarlog/tarlog-plugins#31]
@tarlog can you please create the wiki on your project?
Once done, I think I can edit it (copy things from google code) without bothering your with PRs.
Thanks!

**Comment by tarlog** [comment]
@JnRouvignac 
Created

**Comment by JnRouvignac** [comment]
Weird, for some reason I cannot edit it.
Is the wiki editing restricted? https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by tarlog** [comment]
Try again.

**Comment by JnRouvignac** [comment]
Excellent! Thanks!
